FROM ubuntu:24.04

ARG DEBIAN_FRONTEND=noninteractive

# System essentials
RUN apt-get update
RUN apt-get install -y python3 python3-pip ffmpeg git
RUN apt-get install -y wget
RUN rm -rf /var/lib/apt/lists/*

RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
RUN dpkg -i cuda-keyring_1.1-1_all.deb
RUN apt-get update
RUN apt-get -y install cuda-toolkit-12-8

ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/lib/python3.12/dist-packages/nvidia/cudnn/lib

# Python libraries
RUN pip3 install torch torchvision torchaudio --break-system-packages
RUN pip install fastapi uvicorn[standard] python-multipart --break-system-packages
RUN pip install faster-whisper --break-system-packages

# Workspace setup
WORKDIR /workspace
COPY whisper_service.py /app/

# Expose API port
EXPOSE 8002

# Launch FastAPI Whisper service
CMD ["python3", "-u", "/app/whisper_service.py"]
# CMD ["bash"]