FROM ubuntu:24.04

ARG DEBIAN_FRONTEND=noninteractive

# Install essentials


# Install Python and PIP
RUN apt-get update && apt-get install -y python3 && apt-get install -y python3 python3-pip && rm -rf /var/lib/apt/lists/*

RUN pip3 install torch torchvision --break-system-packages
RUN pip3 install requests --break-system-packages
RUN pip3 install transformers --break-system-packages
RUN pip install Pillow --break-system-packages
RUN pip install accelerate --break-system-packages
RUN pip install -U bitsandbytes --break-system-packages
RUN pip install pillow-heif --break-system-packages
RUN pip install fastapi --break-system-packages
RUN pip install uvicorn[standard] --break-system-packages
RUN pip install python-multipart --break-system-packages

# Set up workspace
WORKDIR /workspace

# Copy your app
COPY app.py /app/

# Expose port
EXPOSE 8001

# Run the app
CMD ["python3", "/app/app.py"]